### ISSUE TITLE
Compatibility with dotnet 8

### ISSUE THREAD

**Issue by filipkral** [MaxRev-Dev/gdal.netcore#119]
**Is your feature request related to a problem? Please describe.**
I would like to migrate my code base to dotnet 8 from dotnet 7 and I wonder if anyone is already using MaxRev-DEV packages with dotnet 8 and what issues it may break.

**Describe the solution you'd like or your ideas here**
I would like to see net8.0 among the compatible target frameworks on https://www.nuget.org/packages/MaxRev.Gdal.Core

**Comment by MaxRev-Dev** [comment]
These packages contain only a small amount of .NET code (under the `compile` folder). They don't require other libraries only the core dotnet runtime. The GDAL drivers are compiled as native libraries for the target system.

Furthermore, It's compatible with `.netstandard`, so you can theoretically use NetFramework, UWP, and  Xamarin. I tried Unity, but this must be resolved (https://github.com/GlitchEnzo/NuGetForUnity/pull/421) because content files are not being preserved.

> what issues it may break.

Nothing should break unless the runtime works as expected. I know that .NET 8 had some memory leaks on ThreadStatics and Serialization. We only use P/Invoke here, so there should be no issues. If at any time you face any performance degradation or memory leaks in .NET8 - consider opening an issue in the dotnet/runtime repo.

I'm already working on the new version in the"ci-automation" branch. Until it shipped, the 3.7.1xx should be considered as the latest release.
