### ISSUE TITLE
Exception while trying to connect to PostgreSQL

### ISSUE THREAD

**Issue by Sythelux** [MaxRev-Dev/gdal.netcore#124]
**Describe the bug**
When doing Ogr.Open with a postgres connection string I get a exception saying `connection to server at "localhost" (127.0.0.1), port 25432 failed: FATAL:  no PostgreSQL user name specified in startup packet`

**To Reproduce**
I attached a minimal Program.cs connecting to a postgis database.

**Expected behavior**
Based on my source code I would expect the Programm to open the database and print layer information.

**Environment information:**
- OS: Linux Mint 21.3 x86_64, which is based on Ubuntu 22.04
- core: "MaxRev.Gdal.Core" Version="3.8.3.286" 
- Runtime: "MaxRev.Gdal.LinuxRuntime.Minimal" Version="3.8.3.286" 

**Additional context**

it is working, when I do `ogrinfo -ro "postgresql://docker:docker@localhost:25432/gis"` I actually suspect a libpq.so being packaged, that my OS doesn't use correctly.

The postgis is running in a docker and is exposed to localhost via port: 25432.

Programm.cs

```csharp
using OSGeo.GDAL;
using OSGeo.OGR;

Ogr.RegisterAll();

DataSource? db = Ogr.Open("PG:dbname=gis host=localhost port=25432 user=docker password=docker", (int)Access.GA_ReadOnly);
// var db = Ogr.Open("postgresql://docker:docker@localhost:25432/gis", (int)Access.GA_ReadOnly); //<-- doesn't work either, when I uncomment
Console.WriteLine(db);
if (db != null)
{
    for (int i = 0; i < db.GetLayerCount(); i++)
    {
        var l = db.GetLayerByIndex(i);
        Console.WriteLine($"{l.GetName()}: {l.GetSpatialRef().GetName()}");
    }
}
else
{
    Console.WriteLine("DB not opened");
}
```

**Comment by MaxRev-Dev** [comment]
1. You didn't read the README. You have to call `GdalBase.ConfigureAll();` instead of `Ogr.RegisterAll();`.
2. Regarding your exception. It's not related to bindings and clearly says there's no **Postgress user name specified**. By default postgis has it's own user which configures the database. So if you get auth exception you have to remove your specified username. Make sure your database is ready.

Here's the modified example. 

`docker run --name postgis-test -e POSTGRES_PASSWORD=user -e POSTGRES_DB=db -p 5432:5432 -d postgis/postgis`

This part I ran in Ubuntu 22.04 with `dotnet8` installed:
```csharp
using MaxRev.Gdal.Core;
using OSGeo.GDAL;
using OSGeo.OGR;

GdalBase.ConfigureAll();

var db = Ogr.Open("PG:dbname=db host=host.docker.internal port=5432 user=postgres password=user", (int)Access.GA_ReadOnly);

Console.WriteLine(db);
if (db != null)
{
    for (int i = 0; i < db.GetLayerCount(); i++)
    {
        var l = db.GetLayerByIndex(i);
        Console.WriteLine($"{l.GetName()}: {l.GetSpatialRef().GetName()}");
    }
}
else
{
    Console.WriteLine("DB not opened");
}
```

Logs: 

<details><summary>C# client</summary>
<p>

<img width="327" alt="image" src="https://github.com/MaxRev-Dev/gdal.netcore/assets/24393967/ed76bfb4-0f6b-4bfe-8410-6f8b33b84be7">

</p>
</details> 

<details><summary>Database</summary>
<p>

<img width="1536" alt="image" src="https://github.com/MaxRev-Dev/gdal.netcore/assets/24393967/1410108c-22ae-4da4-8fab-772a9fc3f128">

</p>
</details>

**Comment by Sythelux** [comment]
no, I haven't read the README. I apologize, but I pretty much started using this package a year ago, because all other packages where a total mess with native bindings and did most stuff in try and error. I adjusted it now.

Thank you for verifying that the issue is not within the package itself. Changing the user to the default postgres user didn't help at all though, but I swapped the docker image I was using kartoza/postgis for some reason. I changed it to postgis/postgis now and it worked. This would've been the last thing to try if you haven't answered. So thank you.
