### ISSUE TITLE
libaec not present in Windows

### ISSUE THREAD

**Issue by antonio-moya** [MaxRev-Dev/gdal.netcore#157]
When version 3.9 is published, libaec dll is not present in windows environements. On the contrary, in Linux runtime environments libace.so is present and working propertly.

**To reproduce:**
Try accessing any grib file of ECMWF's numeric weather models (https://data.ecmwf.int/) wich uses CCSDS compression. Same program works fine in Linux but generates error in Windows.

**Environment information:**
 - OS Windows 11 and Ubuntu 22.04
 - Package version (core): 3.9.1.247
 - Package version (runtime): 3.9.1.247 WindowsRuntime and LinuxRuntime

**Comment by MaxRev-Dev** [comment]
Expected behaviour. It was unintentionally added from Linux system packages. This library is unavailable in VCPKG and GisInternal sources and requires building from sources. This is not a widely used library like GEOS or PROJ so that it won't be worked on.

I suggest trying vscode devcontainers for development (with linux docker containers) or ssh-remote extensions.
