### ISSUE TITLE
MacOS runtime binaries

### ISSUE THREAD

**Issue by Gigas002** [MaxRev-Dev/gdal.netcore#20]
Hello. Just wondering if you're planning to create MacOS binaries package (aka `MaxRev.Gdal.MacOSRuntime.Minimal`). It seems like gdal supports MacOS (judjing by [GitHub Actions](https://github.com/OSGeo/gdal/actions) in Gdal repo).

**Comment by wildwiz** [comment]
+1 :)

**Comment by MaxRev-Dev** [comment]
@Gigas002 @wildwiz 
Well, personally, I did not planned to support MacOS runtime, because my PC is running on Win10 and I have a WSL installed with CentOS, Debian, Ubuntu. At work, I use droplets with Ubuntu/Debian, so for me they are just redundant 😕  
But again, If you want to create and use them - feel free to contribute)

**Comment by wildwiz** [comment]
Hi Max, thank you for your kind answer

I would be more than happy to contribute, but my expertise is all in 
java world.
I am quite inexperienced at Dot Net, putting together libraries and 
builds on a
project of this size unfortunately is well over my head.

However, if my rather limited capabilities can be useful in some way 
please do let me know !
Marco.

**Comment by Gigas002** [comment]
Thanks for detailed answer! I myself don't have an access to MacOS, just wondered is these bindings are planned. If I'll have an opportunity, I'll participate in resolving this problem.
