### ISSUE TITLE
Can't start up on windows

### ISSUE THREAD

**Issue by qjw2bqn** [MaxRev-Dev/gdal.netcore#7]
I restore gdalcoretest.csproj then enter F5 start the project(not the docker-compose method).

the console output the error information:
Trying to configure all twice
Error in MaxRev.Gdal.Core, Version=3.0.1.25, Culture=neutral, PublicKeyToken=null
System.TypeInitializationException: The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'gdal_wrap' or one of its dependencies: 找不到指定的模块。 (Exception from HRESULT: 0x8007007E)
   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_Gdal(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)

but if i use the gdal.core and gdal.core.windowruntime package it work success.

**Comment by MaxRev-Dev** [comment]
Tell me more about your environment, e.g. which OS and .netcore version are you running on?
And can you provide a snapshot of working directory after startup?

**Comment by qjw2bqn** [comment]
win10,
the lastest version of visual studio, both netcore 3.1 and 2.2.
I open the GdalCoreTest.sln use visual studio ,and set the GdalCoreTest as start up project, then F5 run ... ...

the line of "GdalBase.ConfigureAll() "  went wrong.
the message of exception:
The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception.
the stracktrack of exception:
   at OSGeo.GDAL.GdalPINVOKE.SetConfigOption(String jarg1, String jarg2)
   at OSGeo.GDAL.Gdal.SetConfigOption(String pszKey, String pszValue)
   at MaxRev.Gdal.Core.GdalBase.ConfigureAll()
   at GdalCoreTest.Program.Main(String[] args) in C:\Users\Taidy\Downloads\gdal.netcore-master\test\GdalCoreTest\Program.cs:line 15

**Comment by qjw2bqn** [comment]
@MaxRev-Dev 
win10,
the lastest version of visual studio, both netcore 3.1 and 2.2.
I open the GdalCoreTest.sln use visual studio ,and set the GdalCoreTest as start up project, then F5 run ... ...

the line of "GdalBase.ConfigureAll() " went wrong.
the message of exception:
The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception.
the stracktrack of exception:
at OSGeo.GDAL.GdalPINVOKE.SetConfigOption(String jarg1, String jarg2)
at OSGeo.GDAL.Gdal.SetConfigOption(String pszKey, String pszValue)
at MaxRev.Gdal.Core.GdalBase.ConfigureAll()
at GdalCoreTest.Program.Main(String[] args) in C:\Users\Taidy\Downloads\gdal.netcore-master\test\GdalCoreTest\Program.cs:line 15

**Comment by ouyang-means-ouyang** [comment]
I have a question for you? How to create an image not facing north in GDAL? I mean g (2) and G (4) are not zero. Create an image with an angle of 30 or 270 degrees. I hope you can give me an example to teach me how to use these six parameters, especially the definition of rotation parameters

**Comment by skiiasa** [comment]
Even i am facing this issue, I created a test project and installed the 3 nugets
  <PackageReference Include="MaxRev.Gdal.Core" Version="3.0.1.25" />
    <PackageReference Include="MaxRev.Gdal.LinuxRuntime.Minimal" Version="3.0.1.2" />
    <PackageReference Include="MaxRev.Gdal.WindowsRuntime.Minimal" Version="3.0.1.25" />

then in program.cs added this line
GdalBase.ConfigureAll();

created a dockerfile and docker compose- All these steps done in Visual Studio 2019.

Then when i compose and start the project i get the failed to load dll error as mentioned above.

Exception:-
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception.
  Source=MaxRev.Gdal.Core
  StackTrace:
   at OSGeo.GDAL.GdalPINVOKE.SetConfigOption(String jarg1, String jarg2)
   at OSGeo.GDAL.Gdal.SetConfigOption(String pszKey, String pszValue)
   at MaxRev.Gdal.Core.GdalBase.ConfigureAll()
   at GdalTest.Program.Main(String[] args) in C:\code\GdalTest\GdalTest\Program.cs:line 13

Inner Exception 1:
TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.

Inner Exception 2:
DllNotFoundException: Unable to load DLL 'gdal_wrap' or one of its dependencies: The specified module could not be found. (0x8007007E)

Docker file:-
FROM mcr.microsoft.com/dotnet/core/runtime:3.0-nanoserver-1803 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-nanoserver-1803 AS build
WORKDIR /src
COPY ["GdalTest/GdalTest.csproj", "GdalTest/"]
RUN dotnet restore "GdalTest/GdalTest.csproj"
COPY . .
WORKDIR "/src/GdalTest"
RUN dotnet build "GdalTest.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "GdalTest.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GdalTest.dll"]

**Comment by MaxRev-Dev** [comment]
This bug is related to environments without preinstalled VC++ runtime libraries.
If you are using my libraries of version lower than 3.0.1.30, you must install [**vc_redist.x64.exe**](https://aka.ms/vs/16/release/vc_redist.x64.exe)

During the repro on my Win10 VM, I've found some missing CRT libraries - ‘**vcruntime140_1.dll**’ and others.
Here's my feedback on the community forum.
https://developercommunity.visualstudio.com/comments/868043/view.html

A new package with a hotfix is already available for a windows runtime.
[MaxRev.Gdal.WindowsRuntime.Minimal - 3.0.1.35](https://www.nuget.org/packages/MaxRev.Gdal.WindowsRuntime.Minimal/3.0.1.35)

**Comment by MaxRev-Dev** [comment]
> runtime:3.0-nanoserver-1803

As I mentioned above, you must install a VC++ runtime libraries.
But you can't install them into container based on this image.
Alternatively, look at **[microsoft/windowsservercore](https://hub.docker.com/_/microsoft-windows-servercore)** + [vc++ for docker](https://docs.microsoft.com/en-us/visualstudio/install/build-tools-container?view=vs-2019).

Related question on SO: https://stackoverflow.com/a/53432272

**Comment by MaxRev-Dev** [comment]
> How to create an image not facing north in GDAL?

From [GDAL data model docs](https://gdal.org/user/raster_data_model.html#affine-geotransform)

> In case of north up images, the GT(2) and GT(4) coefficients are zero, and the GT(1) is pixel width, and GT(5) is pixel height. The (GT(0),GT(3)) position is the top left corner of the top left pixel of the raster.

So 3rd and 5th define the rotation parameter (with the 2nd and 4th params) if your image doesn't 'north up'.

**Comment by qjw2bqn** [comment]
@MaxRev-Dev i have tested the new package MaxRev.Gdal.WindowsRuntime.Minimal - 3.0.1.35,it's works fine,thanks!
 please commit the lastest code to the github,thanks~

**Comment by abaghum** [comment]
I am using MaxRev.Gdal.Core 3.6.1.120 and MaxRev.Gdal.WindowsRuntime.Minimal 3.6.1.100 and it works on my local windows machine. However, when I create a docker image (linux container) and I replace the WindowsRuntime with LinuxRuntime I get the following error.

System.TypeInitializationException: The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception.\n ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.\n ---> System.DllNotFoundException: Unable to load shared library 'gdal_wrap' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgdal_wrap: cannot open shared object file: No such file or directory\n   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_Gdal(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)\n   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..cctor()\n   --- End of inner exception stack trace ---\n   at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..ctor()\n   at OSGeo.GDAL.GdalPINVOKE..cctor()\n   --- End of inner exception stack trace ---\n   at OSGeo.GDAL.GdalPINVOKE.AllRegister()\n   at OSGeo.GDAL.Gdal.AllRegister()\n   at MaxRev.Gdal.Core.GdalBase.ConfigureGdalDrivers(String gdalDataFolder)\n   at MaxRev.Gdal.Core.GdalBase.ConfigureAll()\n

**Comment by abaghum** [comment]
I am using Red Hat Enterprise and I believe CentOS is built from the source code of Red Hat Enterprise Linux right? and I just read in the FAQ that packages does not work on CentOS 7, Ubuntu 18.04
