### ISSUE TITLE
[BUG] Missing ODBC for MySQL 17 driver

### ISSUE THREAD

**Issue by pendalf45** [MaxRev-Dev/gdal.netcore#85]
**Describe the bug**
Unable to load DLL 'gdal_wrap' or one of its dependencies

````markdown
The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'gdal_wrap' or one of its dependencies: Не найден указанный модуль. (0x8007007E)
````  

**To Reproduce**
Empty console app on net 6.0. Call GdalBase.ConfigureAll();

**Expected behavior**
Gdal initilazed successfully.

**Environment information:**
 - OS (version):  Windows 11 Pro (21H2)
 - Package version (core): 3.6.1.100
 - Package version (runtime): 3.6.1.100
 - .NET version: 6

**Additional context**
3.3.3.120 + windowsRuntime 3.3.3.110 no erros

**Comment by MaxRev-Dev** [comment]
Can't repro with .NET 6.0 on Windows 11. My local build and pipelines [succeed](https://github.com/MaxRev-Dev/gdal.netcore/actions/runs/3761461842/jobs/6393239077) as well. I've also tried cyrillics in path, so that can't be an issue. 
Please, check missing dependencies with dumpbin or [dependency walker](https://www.dependencywalker.com/).
Yoi can find all runtime libraries in `bin/Debug/net6.0`. Check for `gdal_wrap.dll` and its dependencies. Additional logs/information will help me to investigate your problem.

**Comment by MaxRev-Dev** [comment]
I've tested on several environments and still nothing. There can be an issue with CRT dependencies. 
If this issue happens only on your machine, I recommend you try to investigate missing dependencies.
This issue will be closed in several days if it stalls.

**Comment by pendalf45** [comment]
[gdal_wrap.zip](https://github.com/MaxRev-Dev/gdal.netcore/files/10308047/gdal_wrap.zip)

dependency walker "report"

**Comment by MaxRev-Dev** [comment]
This makes sense. ODBC for MySQL driver unintendedly was bound to the windows runtime package.
I will make a patch for this, disabling it. If urgent, you can install [ODBC for MySQL 17 driver](https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16#version-17) to your machine.

**Comment by pendalf45** [comment]
thank you
