### ISSUE TITLE
Fails to load on Azure Web App (Linux) - Missing GLIBC 2.29

### ISSUE THREAD

**Issue by AdamTibi** [MaxRev-Dev/gdal.netcore#87]
Azure Web App (Linux) is failing with LinuxRuntime NuGet v3.6.1.110, v3.6.0.110 and v3.6.0.100 with the error GLIBC 2.29 not found.
But worked with NuGet v3.3.3.120.
Azure Web App has this: 
ASP .NETCore Version: 7.0.0
ldd (Debian **GLIBC 2.28**-10+deb10u2) 2.28

I am assuming this is the problem as v3.3 might be using the older GLIBC. Do you have a work around this?

**Comment by AdamTibi** [comment]
Thank you for the quick response, this is **not** an Azure Function, this is an Azure Web App. To reproduce:

- Create ASP.NET Core 7 Api App and reference the three packages
- Add a call to `GdalBase.ConfigureAll();` in an API
- Deploy to Azure Web App Linux

You will get an error static that the call failed because of missing GLIBC 2.29

**Comment by MaxRev-Dev** [comment]
If I understood correctly, it's an [ASP.NET WebApp](https://learn.microsoft.com/en-us/azure/app-service/quickstart-dotnetcore?tabs=net60&pivots=development-environment-cli) deployed to Azure. So formally, it's related to the Azure environment. 
The real issue is the Glibc version. The main problem with the older versions is that they depend on a lot of packages ([like here](https://github.com/OSGeo/gdal/blob/master/.github/workflows/alpine/start.sh)) to configure for compiling. 
This requires more time to set up everything. I'm not able to recompile these by now. Also, have no experience with Azure, so this will require a reasonable amount of time to solve the problem independently.  I won't work on this because it will only be used occasionally by a community. 
So, there're two options - you can dockerize your app using Debian 11. Or another option is to investigate the issue and rebuild packages on your own using an older libc.

**Comment by AdamTibi** [comment]
I understand and thank you for maintaining this.

**Comment by MaxRev-Dev** [comment]
More on this. One of the main reasons I used Debian 11 is GDAL which [updated](https://github.com/OSGeo/gdal/blob/master/swig/python/README.rst#swig) SWIG of version 4.0. I have not tried to install 4.0 on ['stretch' or 'buster'](https://packages.debian.org/search?searchon=sourcenames&keywords=swig), but it can turn out overwhelming to negotiate that version. Also, this list of package [dependencies](https://github.com/OSGeo/gdal/blob/cc0111e4daf60ac1c6556d7ffff418b5aaf74b12/.github/workflows/ubuntu_18.04/before_install.sh#L25) for Ubuntu18.04 looks no good. Why is this important? GDAL has a lot of dependencies that are prerequisites to the build itself. For example, LibVips uses CentOS7, but [it has a few deps](https://github.com/kleisauke/libvips-packaging/blob/main/linux-x64/Dockerfile) which are relatively easy to setup.

If anyone finds a better, less painful solution to fix this, we can bring it to life. By now, I'll update the docs with cautions/specifics for the runtime environment.
