### ISSUE TITLE
Get count of raster drivers in GDAL

### ISSUE THREAD

**Issue by bertt** [MaxRev-Dev/gdal.netcore#89]
Hi, I was looking at the list of GDAL raster drivers (Gdal.GetDriverCount()), there are 207 drivers but there is a lot of overlap 
with the OGR (vector) drivers (Ogr.GetDriverCount() - 78 drivers). For example  'ESRI Shapefile' is in both lists. 
Is this intentional?

**Comment by MaxRev-Dev** [comment]
I think that this is intentional or defined by the API. There is no API to get a count of the Raster drivers.
If you refer to the [sources](https://github.com/OSGeo/gdal/blob/master/swig/include/gdal.i) or [documentation](https://gdal.org/api/gdaldriver_cpp.html#_CPPv4NK17GDALDriverManager14GetDriverCountEv) the GDAL type returns a count for all defined drivers. There is no API (type) to fetch raster drivers, though OGR is defined to access all vector drivers. 

Also, there's a similar issue from the python bindings on [gisexchange](https://gis.stackexchange.com/questions/402404/getting-available-gdal-raster-drivers-in-python).

An actual count of the raster drivers can be found this way:
```csharp
 Console.WriteLine("OGR Vector Drivers: {0}", Ogr.GetDriverCount());
 var rasterCount = Enumerable
        .Range(0, Gdal.GetDriverCount()).Select(Gdal.GetDriver)
        .Count(x => x.GetMetadataItem("DCAP_RASTER", null) == "YES");
 Console.WriteLine("GDAL Raster Drivers: {0}", rasterCount);

```

**Comment by bertt** [comment]
ok thanks!
